const athletesArray = [
  {
    name: 'Brian Shaw',
    nickname: 'BRAIN',
    height: 80,
    maxBodyweight: 454,
    image:
      'https://www.eatthis.com/wp-content/uploads/sites/4/2022/10/brian-shaw-lifting.jpg?quality=82&strip=all',
    careerDuration: 16,
    bestLifts: {
      deadlift: 1021,
      logPress: 454,
    },
    consistency: 0.754,
    wins: { // FIRST (25 for #1, then 10 each), SECOND (5 each), THIRD (2 each), ... OTHER INT (.2 each)
      worldsStrongestMan: 4, // 2, 4
      arnoldStrongmanClassic: 3, // 4, 0
      strongestManOnEarth: 2, // 2, 0
      rogueInvitational: 0, 
      worldsUltimateStrongman: 0, // 1, 0
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 0, // 0, 1
      otherInternationalComps: 18, // 27 total
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 11,
      deadliftForReps: 11,
      deadliftLadder: 10,
      axleDeadliftForReps: 11,
      hummerTireMaxDeadlift: 11,
      elephantBarMaxDeadlift: 11,
      silverDollarDeadliftForReps: 11,
      armOverArm: 10,
      powerStairs: 8,
      // Squatting = 1/11
      squatForReps: 9,
      squatForMax: 9,
      barrelSquat: 9,
      legPressForReps: 11,
      // Pressing = 2/11
      axlePressForMax: 8,
      axlePressForReps: 9,
      logPressForMax: 9,
      logPressLadder: 8,
      logPressForReps: 9,
      vikingPressForReps: 8,
      dumbbellPressLadder: 7,
      dumbbellPressForReps: 11,
      monsterDumbbellMaxPress: 8,
      bigJerk: 7,
      barrelStandingChestPress: 11,
      // Stone Lifting = 2/11
      atlasStoneRun: 11,
      manhoodStones: 11,
      stoneToShoulder: 8,
      stonePress: 8,
      // Moving = 2/11
      frameCarry: 10,
      farmersWalk: 7,
      superYoke: 11,
      truckPull: 10,
      loadingRace: 8,
      carryAndDrag: 7,
      fingalsFingers: 8,
      tireFlip: 10,
      // Throwing = 1/11
      kegToss: 11,
      weightForHeight: 11,
      steinstossen: 9,
      // Grit = 1/11
      herculesHold: 5,
      wheelOfPain: 3,
      shieldCarry: 8,
      frontHold: 6,
      dinnieStoneWalk: 10,
      conansWheel: 8,
      wreckingBallHold: 5,
    },
    peakRating: 88,
    careerRating: 164, 
  },
  {
    name: 'Žydrūnas Savickas',
    nickname: 'Big Z',
    height: 75,
    maxBodyweight: 412,
    image:
      'https://www.goldmedalpt.com/files/2019/02/mid-shot-Implements_Austrian-Oak-arnold-16_1_.jpg',
    careerDuration: 20,
    bestLifts: {
      deadlift: 972,
      logPress: 509,
    },
    consistency: 0.817,
    wins: { // 15 (25 for #1, then 10 each), 9 (5 each), 3 (2 each), ... 71 (.2 each)
      worldsStrongestMan: 4, // 6, 0
      arnoldStrongmanClassic: 8, // 2, 2
      strongestManOnEarth: 0,
      rogueInvitational: 0, 
      worldsUltimateStrongman: 0,
      IFSAStrongmanWorldChampionships: 2, // 0, 1
      fortissimus: 1, // 1, 0
      otherInternationalComps: 71, 
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 11,
      deadliftForReps: 11,
      deadliftLadder: 10,
      axleDeadliftForReps: 11,
      deadliftForReps: 11,
      hummerTireMaxDeadlift: 11,
      elephantBarMaxDeadlift: 11,
      silverDollarDeadliftForReps: 11,
      armOverArm: 3,
      powerStairs: 10,
      // Squatting = 1/11
      squatForReps: 9,
      squatForMax: 9,
      barrelSquat: 9,
      legPressForReps: 10,
      // Pressing = 2/11
      axlePressForMax: 11,
      axlePressForReps: 11,
      logPressForMax: 11,
      logPressLadder: 11,
      logPressForReps: 11,
      vikingPressForReps: 10,
      dumbbellPressLadder: 10,
      dumbbellPressForReps: 11,
      monsterDumbbellMaxPress: 9,
      bigJerk: 11,
      barrelStandingChestPress: 10,
      // Stone Lifting = 2/11
      atlasStoneRun: 10,
      manhoodStones: 10,
      stoneToShoulder: 8,
      stonePress: 10,
      // Moving = 2/11
      frameCarry: 10,
      farmersWalk: 7,
      superYoke: 11,
      truckPull: 10,
      loadingRace: 9,
      carryAndDrag: 9,
      fingalsFingers: 10,
      tireFlip: 9,
      // Throwing = 1/11
      kegToss: 9,
      weightForHeight: 10,
      steinstossen: 9,
      // Grit = 1/11
      herculesHold: 3,
      wheelOfPain: 6,
      shieldCarry: 5,
      frontHold: 6,
      dinnieStoneWalk: 8,
      conansWheel: 5,
      wreckingBallHold: 3,
    },
    peakRating: 89,
    careerRating: 230,
  },
  {
    name: 'Mariusz Pudzianowski',
    nickname: 'Dominator',
    height: 73,
    maxBodyweight: 313,
    image:
      'https://www.thesun.co.uk/wp-content/uploads/2023/08/260-kilograms-weights-events-called-793836754.jpg?strip=all&w=562',
    careerDuration: 9,
    bestLifts: {
      deadlift: 915,
      logPress: 379,
    },
    consistency: 0.869,
    wins: { // FIRST (25 for #1, then 10 each), SECOND (5 each), THIRD (2 each), ... OTHER INT (.2 each)
      worldsStrongestMan: 5, // 2, 0
      arnoldStrongmanClassic: 0, 
      strongestManOnEarth: 0,
      rogueInvitational: 0, 
      worldsUltimateStrongman: 0,
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 0,
      otherInternationalComps: 38, // 43 total
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 4,
      deadliftForReps: 10,
      deadliftLadder: 6,
      axleDeadliftForReps: 9,
      hummerTireMaxDeadlift: 4,
      elephantBarMaxDeadlift: 4,
      silverDollarDeadliftForReps: 9,
      armOverArm: 9,
      powerStairs: 11,
      // Squatting = 1/11
      squatForReps: 10,
      squatForMax: 5,
      barrelSquat: 8,
      legPressForReps: 8,
      // Pressing = 2/11
      axlePressForMax: 3,
      axlePressForReps: 9,
      logPressForMax: 5,
      logPressLadder: 7,
      logPressForReps: 10,
      vikingPressForReps: 8,
      dumbbellPressLadder: 4,
      dumbbellPressForReps: 4,
      monsterDumbbellMaxPress: 4,
      bigJerk: 5,
      barrelStandingChestPress: 7,
      // Stone Lifting = 2/11
      atlasStoneRun: 10,
      manhoodStones: 8,
      stoneToShoulder: 8,
      stonePress: 6,
      // Moving = 2/11
      frameCarry: 9,
      farmersWalk: 10,
      superYoke: 10,
      truckPull: 9,
      loadingRace: 10,
      carryAndDrag: 11,
      fingalsFingers: 9,
      tireFlip: 9,
      // Throwing = 1/11
      kegToss: 7,
      weightForHeight: 8,
      steinstossen: 8,
      // Grit = 1/11
      herculesHold: 9,
      wheelOfPain: 9,
      shieldCarry: 11,
      frontHold: 9,
      dinnieStoneWalk: 9,
      conansWheel: 11,
      wreckingBallHold: 8,
    },
    peakRating: 80,
    careerRating: 73,
  },
  {
    name: 'Hafþór Björnsson',
    nickname: 'The Mountain',
    height: 81,
    maxBodyweight: 463,
    image:
      'https://live-production.wcms.abc-cdn.net.au/3f4015a42df64e074b747f705fea9166?impolicy=wcms_crop_resize&cropH=627&cropW=1118&xPos=34&yPos=75&width=862&height=485',
    careerDuration: '12+',
    bestLifts: {
      deadlift: 1105,
      logPress: 470,
    },
    consistency: 0.754,
    wins: { // FIRST (25 for #1, then 10 each), SECOND (5 each), THIRD (2 each), ... OTHER INT (.2 each)
      worldsStrongestMan: 1, // 3, 4
      arnoldStrongmanClassic: 3, // 1, 1
      strongestManOnEarth: 0, // 1, 0
      rogueInvitational: 0, // 1, 0
      worldsUltimateStrongman: 1,
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 0,
      otherInternationalComps: 26, // 31 total
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 11,
      deadliftForReps: 10,
      deadliftLadder: 10,
      axleDeadliftForReps: 10,
      hummerTireMaxDeadlift: 11,
      elephantBarMaxDeadlift: 11,
      silverDollarDeadliftForReps: 10,
      armOverArm: 10,
      powerStairs: 10,
      // Squatting = 1/11
      squatForReps: 8,
      squatForMax: 10,
      barrelSquat: 9,
      legPressForReps: 9,
      // Pressing = 2/11
      axlePressForMax: 8,
      axlePressForReps: 10,
      logPressForMax: 7,
      logPressLadder: 7,
      logPressForReps: 6,
      vikingPressForReps: 9,
      dumbbellPressLadder: 9,
      dumbbellPressForReps: 9,
      monsterDumbbellMaxPress: 9,
      bigJerk: 7,
      barrelStandingChestPress: 10,
      // Stone Lifting = 2/11
      atlasStoneRun: 11,
      manhoodStones: 10,
      stoneToShoulder: 8,
      stonePress: 8,
      // Moving = 2/11
      frameCarry: 10,
      farmersWalk: 8,
      superYoke: 10,
      truckPull: 11,
      loadingRace: 10,
      carryAndDrag: 10,
      fingalsFingers: 10,
      tireFlip: 9,
      // Throwing = 1/11
      kegToss: 11,
      weightForHeight: 11,
      steinstossen: 9,
      // Grit = 1/11
      herculesHold: 7,
      wheelOfPain: 9,
      shieldCarry: 9,
      frontHold: 8,
      dinnieStoneWalk: 9,
      conansWheel: 9,
      wreckingBallHold: 10,
    },
    peakRating: 92,
    careerRating: '110+',
  },
  {
    name: 'Eddie Hall',
    nickname: 'The Beast',
    height: 74,
    maxBodyweight: 434,
    image: 'https://i.ytimg.com/vi/x6eC_klO21I/maxresdefault.jpg',
    careerDuration: 6,
    bestLifts: {
      deadlift: 1102,
      logPress: 470,
    },
    consistency: 0.3478,
    wins: { // FIRST (25 for #1, then 10 each), SECOND (5 each), THIRD (2 each), ... OTHER INT (.2 each)
      worldsStrongestMan: 1, // 0, 1
      arnoldStrongmanClassic: 0, 
      strongestManOnEarth: 0,
      rogueInvitational: 0, 
      worldsUltimateStrongman: 0,
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 0,
      otherInternationalComps: 2, // 3 total
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 11,
      deadliftForReps: 9,
      deadliftLadder: 10,
      axleDeadliftForReps: 9,
      hummerTireMaxDeadlift: 10,
      elephantBarMaxDeadlift: 11,
      silverDollarDeadliftForReps: 9,
      armOverArm: 4,
      powerStairs: 5,
      // Squatting = 1/11
      squatForReps: 11,
      squatForMax: 10,
      barrelSquat: 10,
      legPressForReps: 10,
      // Pressing = 2/11
      axlePressForMax: 11,
      axlePressForReps: 9,
      logPressForMax: 9,
      logPressLadder: 9,
      logPressForReps: 9,
      vikingPressForReps: 11,
      dumbbellPressLadder: 5,
      dumbbellPressForReps: 5,
      monsterDumbbellMaxPress: 5,
      bigJerk: 9,
      barrelStandingChestPress: 10,
      // Stone Lifting = 2/11
      atlasStoneRun: 9,
      manhoodStones: 7,
      stoneToShoulder: 7,
      stonePress: 7,
      // Moving = 2/11
      frameCarry: 4,
      farmersWalk: 2,
      superYoke: 7,
      truckPull: 8,
      loadingRace: 3,
      carryAndDrag: 3,
      fingalsFingers: 6,
      tireFlip: 6,
      // Throwing = 1/11
      kegToss: 6,
      weightForHeight: 4,
      steinstossen: 5,
      // Grit = 1/11
      herculesHold: 4,
      wheelOfPain: 4,
      shieldCarry: 7,
      frontHold: 9,
      dinnieStoneWalk: 4,
      conansWheel: 9,
      wreckingBallHold: 4,
    },
    peakRating: 70,
    careerRating: 27,
  },
  {
    name: 'Mitchell Hooper',
    nickname: 'The Moose',
    height: 75,
    maxBodyweight: 325,
    image:
      'https://barbend.com/wp-content/uploads/2024/07/Giants-Strongman-Live.jpg',
    careerDuration: 4,
    bestLifts: {
      deadlift: 1047,
      logPress: 463,
    },
    consistency: 0.9583,
    wins: { // FIRST (25 for #1, then 10 each), SECOND (5 each), THIRD (2 each), ... OTHER INT (.2 each)
      worldsStrongestMan: 1, // 2, 0
      arnoldStrongmanClassic: 3,
      strongestManOnEarth: 1, // 1, 1
      rogueInvitational: 2, // 0, 1
      worldsUltimateStrongman: 0,
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 0,
      otherInternationalComps: 8, // 15 total
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 9,
      deadliftForReps: 10,
      deadliftLadder: 10,
      axleDeadliftForReps: 10,
      hummerTireMaxDeadlift: 9,
      elephantBarMaxDeadlift: 9,
      silverDollarDeadliftForReps: 10,
      armOverArm: 9,
      powerStairs: 9,
      // Squatting = 1/11
      squatForReps: 10,
      squatForMax: 9,
      barrelSquat: 9,
      legPressForReps: 9,
      // Pressing = 2/11
      axlePressForMax: 11,
      axlePressForReps: 10,
      logPressForMax: 8,
      logPressLadder: 9,
      logPressForReps: 9,
      vikingPressForReps: 7,
      dumbbellPressLadder: 8,
      dumbbellPressForReps: 8,
      monsterDumbbellMaxPress: 10,
      bigJerk: 9,
      barrelStandingChestPress: 8,
      // Stone Lifting = 2/11
      atlasStoneRun: 9,
      manhoodStones: 8,
      stoneToShoulder: 9,
      stonePress: 9,
      // Moving = 2/11
      frameCarry: 10,
      farmersWalk: 9,
      superYoke: 11,
      truckPull: 10,
      loadingRace: 9,
      carryAndDrag: 9,
      fingalsFingers: 5,
      tireFlip: 9,
      // Throwing = 1/11
      kegToss: 7,
      weightForHeight: 10,
      steinstossen: 8,
      // Grit = 1/11
      herculesHold: 8,
      wheelOfPain: 8,
      shieldCarry: 10,
      frontHold: 9,
      dinnieStoneWalk: 10,
      conansWheel: 9,
      wreckingBallHold: 8,
    },
    peakRating: 89,
    careerRating: "96+",
  },
  {
    name: 'Tom Stoltman',
    nickname: 'The Albatross',
    height: 80,
    maxBodyweight: 408,
    image: '',
    careerDuration: '7+',
    bestLifts: {
      deadlift: 948,
      logPress: 463,
    },
    consistency: 0,
    wins: { // FIRST (25 for #1, then 10 each), SECOND (5 each), THIRD (2 each), ... OTHER INT (.2 each)
      worldsStrongestMan: 3, // 2, 0
      arnoldStrongmanClassic: 0, // 0, 1
      strongestManOnEarth: 0, // 0, 1
      rogueInvitational: 0, // 3, 0
      worldsUltimateStrongman: 0, // 0, 1
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 0,
      otherInternationalComps: 1, // 4 total
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 7,
      deadliftForReps: 9,
      deadliftLadder: 8,
      axleDeadliftForReps: 8,
      hummerTireMaxDeadlift: 10,
      elephantBarMaxDeadlift: 9,
      silverDollarDeadliftForReps: 9,
      armOverArm: 3,
      powerStairs: 9,
      // Squatting = 1/11
      squatForReps: 4,
      squatForMax: 5,
      barrelSquat: 4,
      legPressForReps: 5,
      // Pressing = 2/11
      axlePressForMax: 10,
      axlePressForReps: 9,
      logPressForMax: 8,
      logPressLadder: 10,
      logPressForReps: 10,
      vikingPressForReps: 8,
      dumbbellPressLadder: 6,
      dumbbellPressForReps: 6,
      monsterDumbbellMaxPress: 8,
      bigJerk: 7,
      barrelStandingChestPress: 4,
      // Stone Lifting = 2/11
      atlasStoneRun: 11,
      manhoodStones: 8,
      stoneToShoulder: 8,
      stonePress: 7,
      // Moving = 2/11
      frameCarry: 7,
      farmersWalk: 5,
      superYoke: 5,
      truckPull: 4,
      loadingRace: 11,
      carryAndDrag: 10,
      fingalsFingers: 10,
      tireFlip: 7,
      // Throwing = 1/11
      kegToss: 10,
      weightForHeight: 10,
      steinstossen: 5,
      // Grit = 1/11
      herculesHold: 2,
      wheelOfPain: 10,
      shieldCarry: 9,
      frontHold: 1,
      dinnieStoneWalk: 6,
      conansWheel: 8,
      wreckingBallHold: 4,
    },
    peakRating: 72,
    careerRating: '76+',
  },
  {
    name: 'Martins Licis',
    nickname: 'The Dragon',
    height: 75,
    maxBodyweight: 355,
    image: '',
    careerDuration: 9,
    bestLifts: {
      deadlift: 970,
      logPress: 441,
    },
    consistency: .7083,
    wins: { // FIRST (25 for #1, then 10 each), SECOND (5 each), THIRD (2 each), ... OTHER INT (.2 each)
      worldsStrongestMan: 1, // 1, 0
      arnoldStrongmanClassic: 1, // 1, 1
      strongestManOnEarth: 0,
      rogueInvitational: 1, 
      worldsUltimateStrongman: 0,
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 0,
      otherInternationalComps: 5, // 8 total
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 8,
      deadliftForReps: 8,
      deadliftLadder: 3,
      axleDeadliftForReps: 8,
      hummerTireMaxDeadlift: 8,
      elephantBarMaxDeadlift: 8,
      silverDollarDeadliftForReps: 8,
      armOverArm: 1,
      powerStairs: 8,
      // Squatting = 1/11
      squatForReps: 10,
      squatForMax: 8,
      barrelSquat: 9,
      legPressForReps: 10,
      // Pressing = 2/11
      axlePressForMax: 7,
      axlePressForReps: 7,
      logPressForMax: 7,
      logPressLadder: 7,
      logPressForReps: 7,
      vikingPressForReps: 7,
      dumbbellPressLadder: 9,
      dumbbellPressForReps: 9,
      monsterDumbbellMaxPress: 8,
      bigJerk: 8,
      barrelStandingChestPress: 6,
      // Stone Lifting = 2/11
      atlasStoneRun: 10,
      manhoodStones: 10,
      stoneToShoulder: 10,
      stonePress: 7,
      // Moving = 2/11
      frameCarry: 9,
      farmersWalk: 8,
      superYoke: 6,
      truckPull: 3,
      loadingRace: 8,
      carryAndDrag: 7,
      fingalsFingers: 7,
      tireFlip: 4,
      // Throwing = 1/11
      kegToss: 2,
      weightForHeight: 6,
      steinstossen: 4,
      // Grit = 1/11
      herculesHold: 7,
      wheelOfPain: 10,
      shieldCarry: 7,
      frontHold: 6,
      dinnieStoneWalk: 7,
      conansWheel: 7,
      wreckingBallHold: 9,
    },
    peakRating: 76,
    careerRating: 58,
  },
  {
    name: 'Bill Kazmaier',
    nickname: 'Kaz',
    height: 74.5,
    maxBodyweight: 326,
    image: '',
    careerDuration: 15,
    bestLifts: {
      deadlift: 915,
      logPress: 375,
    },
    consistency: 0,
    wins: { // FIRST (25 for #1, then 10 each), SECOND (5 each), THIRD (2 each), ... OTHER INT (.2 each)
      worldsStrongestMan: 3, // 1, 1
      arnoldStrongmanClassic: 0, 
      strongestManOnEarth: 0,
      rogueInvitational: 0, 
      worldsUltimateStrongman: 0,
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 0,
      otherInternationalComps: 5, // 8 total
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 11,
      deadliftForReps: 10,
      deadliftLadder: 10,
      axleDeadliftForReps: 10,
      hummerTireMaxDeadlift: 11,
      elephantBarMaxDeadlift: 11,
      silverDollarDeadliftForReps: 10,
      armOverArm: 10,
      powerStairs: 10,
      // Squatting = 1/11
      squatForReps: 10,
      squatForMax: 10,
      barrelSquat: 10,
      legPressForReps: 10,
      // Pressing = 2/11
      axlePressForMax: 10,
      axlePressForReps: 10,
      logPressForMax: 11,
      logPressLadder: 10,
      logPressForReps: 10,
      vikingPressForReps: 10,
      dumbbellPressLadder: 10,
      dumbbellPressForReps: 10,
      monsterDumbbellMaxPress: 10,
      bigJerk: 10,
      barrelStandingChestPress: 10,
      // Stone Lifting = 2/11
      atlasStoneRun: 9,
      manhoodStones: 9,
      stoneToShoulder: 5,
      stonePress: 9,
      // Moving = 2/11
      frameCarry: 10,
      farmersWalk: 8,
      superYoke: 10,
      truckPull: 10,
      loadingRace: 10,
      carryAndDrag: 10,
      fingalsFingers: 10,
      tireFlip: 7,
      // Throwing = 1/11
      kegToss: 10,
      weightForHeight: 10,
      steinstossen: 10,
      // Grit = 1/11
      herculesHold: 10,
      wheelOfPain: 9,
      shieldCarry: 9,
      frontHold: 9,
      dinnieStoneWalk: 9,
      conansWheel: 9,
      wreckingBallHold: 9,
    },
    peakRating: 94,
    careerRating: 53,
  },
  {
    name: 'Mateusz Kieliszkowski',
    nickname: 'The Terminator',
    height: 77,
    maxBodyweight: 330,
    image: '',
    careerDuration: '11+',
    bestLifts: {
      deadlift: 926,
      logPress: 472,
    },
    consistency: 0,
    wins: { // FIRST (25 for #1, then 10 each), SECOND (5 each), THIRD (2 each), ... OTHER INT (.2 each)
      worldsStrongestMan: 0, // 2, 0
      arnoldStrongmanClassic: 0, // 3, 2
      strongestManOnEarth: 0,
      rogueInvitational: 0, // 0, 1
      worldsUltimateStrongman: 1, // 1, 1
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 0,
      otherInternationalComps: 10, // 11 total
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 3,
      deadliftForReps: 3,
      deadliftLadder: 3,
      axleDeadliftForReps: 3,
      hummerTireMaxDeadlift: 4,
      elephantBarMaxDeadlift: 3,
      silverDollarDeadliftForReps: 2,
      armOverArm: 10,
      powerStairs: 3,
      // Squatting = 1/11
      squatForReps: 8,
      squatForMax: 6,
      barrelSquat: 7,
      legPressForReps: 7,
      // Pressing = 2/11
      axlePressForMax: 8,
      axlePressForReps: 9,
      logPressForMax: 9,
      logPressLadder: 9,
      logPressForReps: 9,
      vikingPressForReps: 4,
      dumbbellPressLadder: 11,
      dumbbellPressForReps: 10,
      monsterDumbbellMaxPress: 11,
      bigJerk: 9,
      barrelStandingChestPress: 7,
      // Stone Lifting = 2/11
      atlasStoneRun: 9,
      manhoodStones: 9,
      stoneToShoulder: 11,
      stonePress: 11,
      // Moving = 2/11
      frameCarry: 11,
      farmersWalk: 10,
      superYoke: 10,
      truckPull: 10,
      loadingRace: 9,
      carryAndDrag: 8,
      fingalsFingers: 9,
      tireFlip: 7,
      // Throwing = 1/11
      kegToss: 8,
      weightForHeight: 8,
      steinstossen: 10,
      // Grit = 1/11
      herculesHold: 4,
      wheelOfPain: 10,
      shieldCarry: 10,
      frontHold: 1,
      dinnieStoneWalk: 7,
      conansWheel: 9,
      wreckingBallHold: 5,
    },
    peakRating: 80,
    careerRating: '65+',
  },
  {
    name: 'Laurence Shahlaei',
    nickname: 'Uncle Loz',
    height: 74,
    maxBodyweight: 353,
    image: '',
    careerDuration: 15,
    bestLifts: {
      deadlift: 959,
      logPress: 408,
    },
    consistency: 0,
    wins: {
      worldsStrongestMan: 0, 
      arnoldStrongmanClassic: 0, 
      strongestManOnEarth: 0,
      rogueInvitational: 0, 
      worldsUltimateStrongman: 0,
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 0,
      otherInternationalComps: 8, // 8 total
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 7,
      deadliftForReps: 4,
      deadliftLadder: 6,
      axleDeadliftForReps: 5,
      hummerTireMaxDeadlift: 6,
      elephantBarMaxDeadlift: 6,
      silverDollarDeadliftForReps: 6,
      armOverArm: 5,
      powerStairs: 2,
      // Squatting = 1/11
      squatForReps: 5,
      squatForMax: 5,
      barrelSquat: 5,
      legPressForReps: 5,
      // Pressing = 2/11
      axlePressForMax: 6,
      axlePressForReps: 6,
      logPressForMax: 1,
      logPressLadder: 3,
      logPressForReps: 5,
      vikingPressForReps: 4,
      dumbbellPressLadder: 5,
      dumbbellPressForReps: 5,
      monsterDumbbellMaxPress: 3,
      bigJerk: 3,
      barrelStandingChestPress: 4,
      // Stone Lifting = 2/11
      atlasStoneRun: 5,
      manhoodStones: 4,
      stoneToShoulder: 5,
      stonePress: 4,
      // Moving = 2/11
      frameCarry: 9,
      farmersWalk: 8,
      superYoke: 10,
      truckPull: 9,
      loadingRace: 5,
      carryAndDrag: 5,
      fingalsFingers: 2,
      tireFlip: 5,
      // Throwing = 1/11
      kegToss: 1,
      weightForHeight: 1,
      steinstossen: 2,
      // Grit = 1/11
      herculesHold: 4,
      wheelOfPain: 4,
      shieldCarry: 4,
      frontHold: 4,
      dinnieStoneWalk: 9,
      conansWheel: 4,
      wreckingBallHold: 4,
    },
    peakRating: 47,
    careerRating: 2,
  },
  {
    name: 'Vytautas Lalas',
    nickname: '',
    height: 70,
    maxBodyweight: 324,
    image: '',
    careerDuration: 12,
    bestLifts: {
      deadlift: 0,
      logPress: 0,
    },
    consistency: 0,
    wins: { // FIRST (25 for #1, then 10 each), SECOND (5 each), THIRD (2 each), ... OTHER INT (.2 each)
      worldsStrongestMan: 0, // 1, 0
      arnoldStrongmanClassic: 1, // 0, 1
      strongestManOnEarth: 0,
      rogueInvitational: 0, 
      worldsUltimateStrongman: 0,
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 0,
      otherInternationalComps: 6, // 8 total
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 8,
      deadliftForReps: 9,
      deadliftLadder: 9,
      axleDeadliftForReps: 9,
      hummerTireMaxDeadlift: 8,
      elephantBarMaxDeadlift: 8,
      silverDollarDeadliftForReps: 9,
      armOverArm: 5,
      powerStairs: 6,
      // Squatting = 1/11
      squatForReps: 10,
      squatForMax: 8,
      barrelSquat: 9,
      legPressForReps: 9,
      // Pressing = 2/11
      axlePressForMax: 7,
      axlePressForReps: 7,
      logPressForMax: 7,
      logPressLadder: 8,
      logPressForReps: 9,
      vikingPressForReps: 7,
      dumbbellPressLadder: 9,
      dumbbellPressForReps: 10,
      monsterDumbbellMaxPress: 8,
      bigJerk: 8,
      barrelStandingChestPress: 6,
      // Stone Lifting = 2/11
      atlasStoneRun: 7,
      manhoodStones: 9,
      stoneToShoulder: 8,
      stonePress: 8,
      // Moving = 2/11
      frameCarry: 9,
      farmersWalk: 5,
      superYoke: 9,
      truckPull: 6,
      loadingRace: 8,
      carryAndDrag: 2,
      fingalsFingers: 4,
      tireFlip: 2,
      // Throwing = 1/11
      kegToss: 7,
      weightForHeight: 5,
      steinstossen: 5,
      // Grit = 1/11
      herculesHold: 4,
      wheelOfPain: 4,
      shieldCarry: 5,
      frontHold: 3,
      dinnieStoneWalk: 4,
      conansWheel: 3,
      wreckingBallHold: 4,
    },
    peakRating: 66.5,
    careerRating: 33,
  },
  {
    name: 'Derek Poundstone',
    nickname: '',
    height: 73,
    maxBodyweight: 341,
    image: '',
    careerDuration: 7,
    bestLifts: {
      deadlift: 0,
      logPress: 0,
    },
    consistency: 0,
    wins: { // FIRST (25 for #1, then 10 each), SECOND (5 each), THIRD (2 each), ... OTHER INT (.2 each)
      worldsStrongestMan: 0, // 1, 0
      arnoldStrongmanClassic: 2, // 2, 0
      strongestManOnEarth: 0,
      rogueInvitational: 0, 
      worldsUltimateStrongman: 0,
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 1, // 1, 0
      otherInternationalComps: 5,
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 7,
      deadliftForReps: 10,
      deadliftLadder: 8,
      axleDeadliftForReps: 9,
      hummerTireMaxDeadlift: 8,
      elephantBarMaxDeadlift: 7,
      silverDollarDeadliftForReps: 10,
      armOverArm: 4,
      powerStairs: 9,
      // Squatting = 1/11
      squatForReps: 6,
      squatForMax: 6,
      barrelSquat: 6,
      legPressForReps: 6,
      // Pressing = 2/11
      axlePressForMax: 7,
      axlePressForReps: 9,
      logPressForMax: 8,
      logPressLadder: 9,
      logPressForReps: 10,
      vikingPressForReps: 6,
      dumbbellPressLadder: 11,
      dumbbellPressForReps: 11,
      monsterDumbbellMaxPress: 10,
      bigJerk: 9,
      barrelStandingChestPress: 9,
      // Stone Lifting = 2/11
      atlasStoneRun: 9,
      manhoodStones: 9,
      stoneToShoulder: 7,
      stonePress: 8,
      // Moving = 2/11
      frameCarry: 8,
      farmersWalk: 10,
      superYoke: 10,
      truckPull: 8,
      loadingRace: 10,
      carryAndDrag: 9,
      fingalsFingers: 7,
      tireFlip: 5,
      // Throwing = 1/11
      kegToss: 4,
      weightForHeight: 4,
      steinstossen: 7,
      // Grit = 1/11
      herculesHold: 4,
      wheelOfPain: 8,
      shieldCarry: 8,
      frontHold: 10,
      dinnieStoneWalk: 8,
      conansWheel: 8,
      wreckingBallHold: 4,
    },
    peakRating: 77,
    careerRating: 61,
  },
  {
    name: 'Trey Mitchell',
    nickname: 'The Big Thicket',
    height: 76,
    maxBodyweight: 364,
    image: '',
    careerDuration: 0,
    bestLifts: {
      deadlift: 1036,
      logPress: 461,
    },
    consistency: 0,
    wins: { // FIRST (25 for #1, then 10 each), SECOND (5 each), THIRD (2 each), ... OTHER INT (.2 each)
      worldsStrongestMan: 0, 
      arnoldStrongmanClassic: 0, 
      strongestManOnEarth: 2,
      rogueInvitational: 0, // 1, 0
      worldsUltimateStrongman: 0,
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 0,
      otherInternationalComps: 2, // 4 total
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 9,
      deadliftForReps: 10,
      deadliftLadder: 8,
      axleDeadliftForReps: 10,
      hummerTireMaxDeadlift: 9,
      elephantBarMaxDeadlift: 7,
      silverDollarDeadliftForReps: 9,
      armOverArm: 7,
      powerStairs: 3,
      // Squatting = 1/11
      squatForReps: 9,
      squatForMax: 6,
      barrelSquat: 7,
      legPressForReps: 9,
      // Pressing = 2/11
      axlePressForMax: 9,
      axlePressForReps: 9,
      logPressForMax: 10,
      logPressLadder: 10,
      logPressForReps: 10,
      vikingPressForReps: 9,
      dumbbellPressLadder: 8,
      dumbbellPressForReps: 9,
      monsterDumbbellMaxPress: 8,
      bigJerk: 9,
      barrelStandingChestPress: 4,
      // Stone Lifting = 2/11
      atlasStoneRun: 11,
      manhoodStones: 7,
      stoneToShoulder: 8,
      stonePress: 8,
      // Moving = 2/11
      frameCarry: 2,
      farmersWalk: 1,
      superYoke: 9,
      truckPull: 3,
      loadingRace: 2,
      carryAndDrag: 5,
      fingalsFingers: 8,
      tireFlip: 6,
      // Throwing = 1/11
      kegToss: 10,
      weightForHeight: 3,
      steinstossen: 3,
      // Grit = 1/11
      herculesHold: 5,
      wheelOfPain: 9,
      shieldCarry: 7,
      frontHold: 6,
      dinnieStoneWalk: 2,
      conansWheel: 5,
      wreckingBallHold: 6,
    },
    peakRating: 69,
    careerRating: '40+',
  },
  {
    name: 'Oleksii Novikov',
    nickname: '',
    height: 73,
    maxBodyweight: 306,
    image: '',
    careerDuration: '7+',
    bestLifts: {
      deadlift: 1000,
      logPress: 421,
    },
    consistency: 0,
    wins: { // FIRST (25 for #1, then 10 each), SECOND (5 each), THIRD (2 each), ... OTHER INT (.2 each)
      worldsStrongestMan: 1, // 0, 2 
      arnoldStrongmanClassic: 0, // 1, 0
      strongestManOnEarth: 0, // 0, 1
      rogueInvitational: 1, // 0, 1
      worldsUltimateStrongman: 2,
      IFSAStrongmanWorldChampionships: 0,
      fortissimus: 0,
      otherInternationalComps: 8, // 11 total
    },
    skills: {
      // Pulling = 2/11
      deadliftForMax: 6,
      deadliftForReps: 10,
      deadliftLadder: 9,
      axleDeadliftForReps: 10,
      hummerTireMaxDeadlift: 10,
      elephantBarMaxDeadlift: 5,
      silverDollarDeadliftForReps: 10,
      armOverArm: 8,
      powerStairs: 4,
      // Squatting = 1/11
      squatForReps: 5,
      squatForMax: 6,
      barrelSquat: 5,
      legPressForReps: 3,
      // Pressing = 2/11
      axlePressForMax: 6,
      axlePressForReps: 6,
      logPressForMax: 6,
      logPressLadder: 8,
      logPressForReps: 10,
      vikingPressForReps: 7,
      dumbbellPressLadder: 11,
      dumbbellPressForReps: 11,
      monsterDumbbellMaxPress: 10,
      bigJerk: 1,
      barrelStandingChestPress: 2,
      // Stone Lifting = 2/11
      atlasStoneRun: 9,
      manhoodStones: 6,
      stoneToShoulder: 9,
      stonePress: 7,
      // Moving = 2/11
      frameCarry: 8,
      farmersWalk: 9,
      superYoke: 10,
      truckPull: 2,
      loadingRace: 10,
      carryAndDrag: 5,
      fingalsFingers: 9,
      tireFlip: 7,
      // Throwing = 1/11
      kegToss: 6,
      weightForHeight: 5,
      steinstossen: 5,
      // Grit = 1/11
      herculesHold: 7,
      wheelOfPain: 8,
      shieldCarry: 9,
      frontHold: 5,
      dinnieStoneWalk: 5,
      conansWheel: 9,
      wreckingBallHold: 9,
    },
    peakRating: 72,
    careerRating: '70+',
  },
];

export { athletesArray };
